server:
  port: 8090
  error:
    include-message: always

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: item-service-route
          uri: lb://item-service
          predicates:
            - Path=/api/v1/items/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
