# Trabajando con Resilience4J
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      # productos, id que le damos al circuit breaker
      productos:
        base-config: defecto
  # Configurando el TimeOut
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      # productos, id que le damos al circuit breaker
      productos:
        base-config: defecto

# Configuraciones de Spring Cloud Gateway: predicados, filtros
spring:
  cloud:
    gateway:
      routes:
        - id: ms-productos
          # lb: Load Balanced, es decir accederemos al ms productos mediante Load Balanced
          uri: lb://ms-productos
          predicates:
            - Path=/api-base/productos-base/**
          filters:
            # productos, id que le pusimos al Circuit Breaker en la configuración superior (resilience4j)
            # statusCodes: 500, para que pueda manejar el "Internal Server Error" status 500
            # fallbackUri, da un servicio alternativo cuando se abra el circuito. Tiene que ser uno distinto al
            # cual falla, porque si no se estará llamando de manera recursiva en un ciclo infinito
            - name: CircuitBreaker
              args:
                name: productos
                statusCodes: 500
                fallbackUri: forward:/api-base/items-base/api/v1/items/producto/5/cantidad/5
            # 2, porque el path (/api-base/productos-base/**) está compuesta por 2 segmentos: api-base y productos-base
            - StripPrefix=2
            # Aplicando este filtro solo a ms-productos
            # Ejemplo, corresponde al prefijo del nombre de la clase que creamos: EjemploGatewayFilterFactory
            # El orden en que enviamos los parámetros lo está definiendo el método shortcutFieldOrder() del filtro personalizado.
            - EjemploNuevoNombreFiltroCookie=Hola este es mi mensaje personalizado, usuario, magadiflo
        - id: ms-items
          uri: lb://ms-items
          predicates:
            - Path=/api-base/items-base/**
          filters:
            - StripPrefix=2
            # Filtros que vienen de fábrica en Spring Cloud Gateway
            - AddRequestHeader=token-req, 987654
            - AddResponseHeader=token-resp, 456123
            - AddRequestParameter=nombre, Martin
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api-base/usuarios-base/**
          filters:
            - StripPrefix=2