spring.application.name=ms-items
server.port=8002

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Configuración al servidor de configuraciones
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=development

# Habilita los endpoints de Spring Actuator
management.endpoints.web.exposure.include=*

# Probabilidad de exportar trazas. Cambiamos el 0.1 por defecto al 1
spring.sleuth.sampler.probability=1.0
# Opcional, configurar ruta del servidor zipkin
spring.zipkin.base-url=http://127.0.0.1:9411/