version: "3.9"
services:
  config-server:
    container_name: config-server
    image: config-server:v1.0.0
    ports:
      - "8888:8888"
    env_file:
      - ./infrastructure/ms-config-server/.env
    restart: always
    networks:
      - ms-spring-cloud
  eureka-server:
    container_name: eureka-server
    image: eureka-server:v1.0.0
    ports:
      - "8761:8761"
    restart: always
    networks:
      - ms-spring-cloud
  ms-mysql8:
    container_name: ms-mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: magadiflo
      MYSQL_DATABASE: bd_spring_boot_cloud
    restart: always
    networks:
      - ms-spring-cloud
  ms-productos:
    image: ms-productos:v1.0.0
    restart: always
    networks:
      - ms-spring-cloud
    depends_on:
      - config-server
      - eureka-server
      - ms-mysql8
  ms-items:
    container_name: ms-items
    image: ms-items:v1.0.0
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks:
      - ms-spring-cloud
    depends_on:
      - config-server
      - eureka-server
      - ms-productos
  ms-zuul-server:
    container_name: ms-zuul-server
    image: ms-zuul-server:v1.0.0
    ports:
      - "8090:8090"
    restart: always
    networks:
      - ms-spring-cloud
    depends_on:
      - config-server
      - eureka-server
      - ms-productos
      - ms-items
networks:
  ms-spring-cloud:
    name: ms-spring-cloud