spring.application.name=ms-productos
server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Configuración al servidor de configuraciones
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=development

# Mostrar error completo en response
server.error.include-message=always