spring.application.name=ms-productos
server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Configuración al servidor de configuraciones
spring.config.import=optional:configserver:http://localhost:8888

# Datasource MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_spring_boot_cloud?serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=magadiflo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurando dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Generando tablas: create, crea el esquema y destruye cualquier dato previo
spring.jpa.hibernate.ddl-auto=create

# Vista y formato en el log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mostrar error completo en response
server.error.include-message=always