server:
  port: 8001
  error:
    include-message: always

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_product_service?serverTimezone=America/Lima
    username: root
    password: magadiflo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
