server:
  port: 8002
  error:
    include-message: always

spring:
  application:
    name: item-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

custom:
  base-url:
    product-service: lb://product-service/api/v1/products
