server:
  port: 8002
  error:
    include-message: always

spring:
  application:
    name: item-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            product-service:
              - uri: http://localhost:8010
              - uri: http://localhost:8011
              - uri: http://localhost:8012
