spring.application.name=ms-items
server.port=8002

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Como hystrix envuelve a ribbon, lo ideal es que hystrix tenga un tiempo de timeout superior a ribbon.
# Por lo tanto, en la siguiente configuración hystrix = 20000, Ribbon = 3000 + 10000 => hystrix (20000) > ribbon (13000)
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon.ConnectTimeout: 3000
#ribbon.ReadTimeout: 10000