spring.application.name=ms-zuul-server
server.port=8090

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# nombre de la ruta: productos (..routes.productos.. <--- ese es, podemos darle cualquier nombre)
# Service-id (id del servicio): ms-productos
# Cada vez que queramos acceder al ms-productos a través de Zuul, debemos colocar la ruta base(el del path)
# Después de la ruta base, vendrían las rutas propias del ms-productos
# Ruta base: /api-base/productos-base/
# **, indica las rutas propias del microservicio
# Path de Zuul + Path del ms-productos: http://127.0.0.1:8090/api-base/productos-base/api/v1/productos
zuul.routes.productos.service-id=ms-productos
zuul.routes.productos.path=/api-base/productos-base/**

zuul.routes.items.service-id=ms-items
zuul.routes.items.path=/api-base/items-base/**

zuul.routes.usuarios.service-id=ms-usuarios
zuul.routes.usuarios.path=/api-base/usuarios-base/**

zuul.routes.security.service-id=ms-authorization-server
zuul.routes.security.path=/api-base/authorization-server-base/**
zuul.routes.security.sensitive-headers=Cookie,Set-Cookie

# Configuracion al servidor de configuraciones
spring.config.import=optional:configserver:http://config-server:8888
# Habilita los endpoints de Spring Actuator
management.endpoints.web.exposure.include=*

# Probabilidad de exportar trazas. Cambiamos el 0.1 por defecto al 1
spring.sleuth.sampler.probability=1.0