server:
  port: 8888
  error:
    include-message: always

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/magadiflo/config-server-repo.git
