server:
  port: 8888
  error:
    include-message: always

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/programming/spring/01.udemy/02.andres_guzman/06.microservices_netflix_eureka/config-server-repo
