spring.application.name=ms-config-server
server.port=8888

# Repositorio Local
# En windows es 3 ///, en linux o mac 1 /
#spring.cloud.config.server.git.uri=file:///M:/PROGRAMACION/DESARROLLO_JAVA_SPRING/INTELLIJ_IDEA/01.udemy/02.udemy_andres_guzman/04.repaso/config-server-repo

# Repositorio Remoto
spring.cloud.config.server.git.uri=https://github.com/magadiflo/config-server-repo.git