spring.application.name=ms-usuarios
server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.format_sql=true

# Configurando conexion a servidor de configuraciones
spring.config.import=optional:configserver:http://config-server:8888
spring.profiles.active=development

# Probabilidad de exportar trazas. Cambiamos el 0.1 por defecto al 1
spring.sleuth.sampler.probability=1.0