spring.application.name=ms-usuarios
server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.format_sql=true

# Configurando conexion a servidor de configuraciones
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=development